"""add daily_focus and focus_items

Revision ID: 6074e1776d7c
Revises: 04b030ef91fc
Create Date: 2026-06-08 22:28:41.199165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6074e1776d7c'
down_revision: Union[str, None] = '04b030ef91fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_focus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('intencion', sa.String(length=255), nullable=True),
    sa.Column('energia_nivel', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fecha', name='uq_daily_focus_user_fecha')
    )
    with op.batch_alter_table('daily_focus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_focus_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_focus_user_id'), ['user_id'], unique=False)

    op.create_table('focus_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_focus_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('from_calendar', sa.Boolean(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['daily_focus_id'], ['daily_focus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_items_daily_focus_id'), ['daily_focus_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focus_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_items_daily_focus_id'))

    op.drop_table('focus_items')
    with op.batch_alter_table('daily_focus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_focus_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_focus_fecha'))

    op.drop_table('daily_focus')
    # ### end Alembic commands ###
