"""add daily_reflections and wins

Revision ID: ab9edab8ac35
Revises: 6074e1776d7c
Create Date: 2026-06-08 22:41:47.202567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9edab8ac35'
down_revision: Union[str, None] = '6074e1776d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reflections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_focus_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('que_funciono', sa.Text(), nullable=True),
    sa.Column('que_bloqueo', sa.Text(), nullable=True),
    sa.Column('aprendizaje', sa.Text(), nullable=True),
    sa.Column('ajuste_manana', sa.Text(), nullable=True),
    sa.Column('estado_animo', sa.String(length=50), nullable=True),
    sa.Column('energia_final', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['daily_focus_id'], ['daily_focus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fecha', name='uq_reflections_user_fecha')
    )
    with op.batch_alter_table('daily_reflections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reflections_user_id'), ['user_id'], unique=False)

    op.create_table('wins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('daily_focus_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('impacto', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['daily_focus_id'], ['daily_focus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wins_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wins_user_id'))

    op.drop_table('wins')
    with op.batch_alter_table('daily_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reflections_user_id'))

    op.drop_table('daily_reflections')
    # ### end Alembic commands ###
